"use client"

import { useState, useRef } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"
import { ScrollArea } from "@/components/ui/scroll-area"
import {
  FileText,
  Download,
  Printer,
  Loader2,
  Calendar,
  AlertTriangle,
  CheckCircle,
  TrendingUp,
  Brain,
  Target,
  ClipboardList,
  Share2,
  RefreshCw,
  Sparkles,
  Activity,
  BarChart3,
} from "lucide-react"
import { cn } from "@/lib/utils"
import ReactMarkdown from "react-markdown"

interface ReportData {
  generatedAt: string
  userName: string
  userEmail: string
  latestScreening: {
    date: string
    riskLevel: string
    probability: number
    confidence: string
    aq10Total: number
    socialScore: number
    attentionScore: number
    physicalScore?: number
    physicalReason?: string
    speechScore?: number
    speechReason?: string
    contributingFactors: { feature: string; importance: number; direction: string }[]
    demographics?: { age?: number; gender?: string }
  }
  screeningHistory: {
    date: string
    riskLevel: string
    probability: number
  }[]
  therapyProgress: {
    totalTasks: number
    completedTasks: number
    completionRate: number | string
    tasksByCategory: Record<string, number>
    completedByCategory: Record<string, number>
    recentCompletedTasks: {
      title: string
      category: string
      completedAt: string
    }[]
  }
  clinicalSummary: string
}

export default function ReportsPage() {
  const [isGenerating, setIsGenerating] = useState(false)
  const [report, setReport] = useState<ReportData | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [includeTherapyProgress, setIncludeTherapyProgress] = useState(true)
  const [includeRecommendations, setIncludeRecommendations] = useState(true)
  const reportRef = useRef<HTMLDivElement>(null)

  const generateReport = async () => {
    setIsGenerating(true)
    setError(null)

    try {
      const response = await fetch("/api/generate-report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          includeTherapyProgress,
          includeRecommendations,
        }),
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate report")
      }

      setReport(data.report)
    } catch (err) {
      setError(err instanceof Error ? err.message : "An error occurred")
    } finally {
      setIsGenerating(false)
    }
  }

  const handlePrint = () => {
    window.print()
  }

  const handleDownload = () => {
    if (!report) return

    // Create a text version of the report
    const reportText = `
NEUROSCREEN CLINICAL REPORT
Generated: ${formatDate(report.generatedAt)}
Patient: ${report.userName}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

LATEST SCREENING RESULTS
------------------------
Date: ${formatDate(report.latestScreening.date)}
Risk Level: ${report.latestScreening.riskLevel}
Probability: ${(report.latestScreening.probability * 100).toFixed(1)}%
Confidence: ${report.latestScreening.confidence}

Scores:
- AQ-10 Total: ${report.latestScreening.aq10Total || 'N/A'}
- Social Score: ${report.latestScreening.socialScore || 'N/A'}
- Attention Score: ${report.latestScreening.attentionScore || 'N/A'}
${report.latestScreening.physicalScore ? `- Physical Score: ${report.latestScreening.physicalScore}/5` : ''}
${report.latestScreening.speechScore ? `- Speech Score: ${report.latestScreening.speechScore}/5` : ''}

Top Contributing Factors:
${report.latestScreening.contributingFactors.slice(0, 5).map(f => `- ${f.feature}: ${f.importance.toFixed(1)}% (${f.direction})`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

THERAPY PROGRESS
----------------
Total Tasks: ${report.therapyProgress.totalTasks}
Completed: ${report.therapyProgress.completedTasks}
Completion Rate: ${report.therapyProgress.completionRate}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CLINICAL SUMMARY
----------------
${report.clinicalSummary}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DISCLAIMER: This report is generated by NeuroScreen, an AI-powered autism screening tool. 
It is NOT a medical diagnosis. Please consult with qualified healthcare professionals 
for proper evaluation and diagnosis.
`

    const blob = new Blob([reportText], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `neuroscreen-report-${new Date().toISOString().split("T")[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })
  }

  const getRiskColor = (riskLevel: string) => {
    switch (riskLevel) {
      case "High":
        return "text-red-500 bg-red-50 dark:bg-red-950"
      case "Moderate":
        return "text-amber-500 bg-amber-50 dark:bg-amber-950"
      case "Low":
        return "text-green-500 bg-green-50 dark:bg-green-950"
      default:
        return "text-gray-500 bg-gray-50 dark:bg-gray-950"
    }
  }

  const getRiskIcon = (riskLevel: string) => {
    switch (riskLevel) {
      case "High":
        return <AlertTriangle className="h-5 w-5" />
      case "Moderate":
        return <Activity className="h-5 w-5" />
      case "Low":
        return <CheckCircle className="h-5 w-5" />
      default:
        return <Brain className="h-5 w-5" />
    }
  }

  return (
    <div className="max-w-6xl mx-auto space-y-8 pb-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-2xl md:text-3xl font-bold flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-500 shadow-lg shadow-emerald-500/25">
              <FileText className="h-6 w-6 text-white" />
            </div>
            Clinical Reports
          </h1>
          <p className="text-muted-foreground mt-1">
            Generate comprehensive reports to share with healthcare providers
          </p>
        </div>
      </div>

      {/* Report Generation Card */}
      {!report && (
        <div className="relative">
          {/* Background decoration */}
          <div className="absolute inset-0 bg-gradient-to-r from-emerald-500/5 via-teal-500/5 to-cyan-500/5 rounded-3xl blur-xl" />

          <Card className="relative border-0 shadow-2xl overflow-hidden bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm">
            {/* Decorative top gradient bar */}
            <div className="h-1.5 bg-gradient-to-r from-emerald-500 via-teal-500 to-cyan-500" />

            <CardHeader className="pb-2 pt-8">
              <div className="flex items-center justify-center mb-4">
                <div className="relative">
                  <div className="absolute inset-0 bg-gradient-to-r from-emerald-500 to-teal-500 rounded-full blur-xl opacity-50 animate-pulse" />
                  <div className="relative p-4 rounded-full bg-gradient-to-br from-emerald-500 to-teal-500 shadow-lg">
                    <Sparkles className="h-8 w-8 text-white" />
                  </div>
                </div>
              </div>
              <CardTitle className="text-2xl text-center">Generate New Report</CardTitle>
              <CardDescription className="text-center max-w-md mx-auto">
                Create an AI-powered clinical summary of your screening results and therapy progress
              </CardDescription>
            </CardHeader>

            <CardContent className="space-y-8 px-8 pb-8">
              {/* Options */}
              <div className="space-y-4">
                <h4 className="font-semibold text-sm text-muted-foreground uppercase tracking-wider text-center">
                  Report Options
                </h4>
                <div className="grid md:grid-cols-2 gap-4 max-w-2xl mx-auto">
                  <div
                    className={cn(
                      "flex items-center justify-between p-4 rounded-2xl border-2 transition-all cursor-pointer",
                      includeTherapyProgress
                        ? "border-emerald-500 bg-emerald-50 dark:bg-emerald-950/30"
                        : "border-border hover:border-emerald-300"
                    )}
                    onClick={() => setIncludeTherapyProgress(!includeTherapyProgress)}
                  >
                    <div className="flex items-center gap-3">
                      <div className={cn(
                        "p-2 rounded-xl transition-colors",
                        includeTherapyProgress
                          ? "bg-emerald-500 text-white"
                          : "bg-slate-100 dark:bg-slate-800 text-muted-foreground"
                      )}>
                        <Target className="h-5 w-5" />
                      </div>
                      <div>
                        <Label htmlFor="therapy-progress" className="font-medium cursor-pointer">
                          Therapy Progress
                        </Label>
                        <p className="text-xs text-muted-foreground">Include task completion data</p>
                      </div>
                    </div>
                    <Switch
                      id="therapy-progress"
                      checked={includeTherapyProgress}
                      onCheckedChange={setIncludeTherapyProgress}
                    />
                  </div>

                  <div
                    className={cn(
                      "flex items-center justify-between p-4 rounded-2xl border-2 transition-all cursor-pointer",
                      includeRecommendations
                        ? "border-teal-500 bg-teal-50 dark:bg-teal-950/30"
                        : "border-border hover:border-teal-300"
                    )}
                    onClick={() => setIncludeRecommendations(!includeRecommendations)}
                  >
                    <div className="flex items-center gap-3">
                      <div className={cn(
                        "p-2 rounded-xl transition-colors",
                        includeRecommendations
                          ? "bg-teal-500 text-white"
                          : "bg-slate-100 dark:bg-slate-800 text-muted-foreground"
                      )}>
                        <ClipboardList className="h-5 w-5" />
                      </div>
                      <div>
                        <Label htmlFor="recommendations" className="font-medium cursor-pointer">
                          Recommendations
                        </Label>
                        <p className="text-xs text-muted-foreground">AI-generated next steps</p>
                      </div>
                    </div>
                    <Switch
                      id="recommendations"
                      checked={includeRecommendations}
                      onCheckedChange={setIncludeRecommendations}
                    />
                  </div>
                </div>
              </div>

              {error && (
                <div className="p-4 rounded-2xl bg-red-50 dark:bg-red-950/50 border border-red-200 dark:border-red-800 text-red-600 dark:text-red-400 text-sm max-w-2xl mx-auto">
                  <div className="flex items-center gap-3">
                    <div className="p-2 rounded-full bg-red-100 dark:bg-red-900">
                      <AlertTriangle className="h-4 w-4" />
                    </div>
                    <div>
                      <p className="font-medium">Error generating report</p>
                      <p className="text-xs opacity-80">{error}</p>
                    </div>
                  </div>
                </div>
              )}

              <div className="flex flex-col items-center gap-4">
                <Button
                  onClick={generateReport}
                  disabled={isGenerating}
                  size="lg"
                  className="h-14 px-10 text-lg rounded-2xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 shadow-lg shadow-emerald-500/25 hover:shadow-xl hover:shadow-emerald-500/30 transition-all hover:scale-105"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="h-5 w-5 animate-spin mr-2" />
                      Generating Report...
                    </>
                  ) : (
                    <>
                      <FileText className="h-5 w-5 mr-2" />
                      Generate Clinical Report
                    </>
                  )}
                </Button>

                <p className="text-xs text-muted-foreground text-center max-w-sm">
                  Reports include AI-generated summaries and are intended to support, not replace,
                  professional medical advice.
                </p>
              </div>

              {/* Features preview */}
              <div className="grid grid-cols-3 gap-4 pt-4 border-t max-w-2xl mx-auto">
                <div className="text-center">
                  <div className="mx-auto w-10 h-10 rounded-xl bg-teal-100 dark:bg-teal-900/30 flex items-center justify-center mb-2">
                    <Brain className="h-5 w-5 text-teal-500" />
                  </div>
                  <p className="text-xs font-medium">AI Analysis</p>
                  <p className="text-[10px] text-muted-foreground">Powered by LLM</p>
                </div>
                <div className="text-center">
                  <div className="mx-auto w-10 h-10 rounded-xl bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center mb-2">
                    <BarChart3 className="h-5 w-5 text-purple-500" />
                  </div>
                  <p className="text-xs font-medium">Visual Data</p>
                  <p className="text-[10px] text-muted-foreground">Charts & metrics</p>
                </div>
                <div className="text-center">
                  <div className="mx-auto w-10 h-10 rounded-xl bg-pink-100 dark:bg-pink-900/30 flex items-center justify-center mb-2">
                    <Download className="h-5 w-5 text-pink-500" />
                  </div>
                  <p className="text-xs font-medium">Export Ready</p>
                  <p className="text-[10px] text-muted-foreground">Print or download</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Generated Report */}
      {report && (
        <div className="space-y-6 print:space-y-4" ref={reportRef}>
          {/* Report Actions */}
          <div className="flex flex-wrap gap-2 print:hidden">
            <Button variant="outline" onClick={handlePrint} className="gap-2">
              <Printer className="h-4 w-4" />
              Print
            </Button>
            <Button variant="outline" onClick={handleDownload} className="gap-2">
              <Download className="h-4 w-4" />
              Download
            </Button>
            <Button
              variant="outline"
              onClick={() => setReport(null)}
              className="gap-2 ml-auto"
            >
              <RefreshCw className="h-4 w-4" />
              New Report
            </Button>
          </div>

          {/* Report Header */}
          <Card className="border-0 shadow-lg print:shadow-none print:border">
            <CardHeader className="bg-gradient-to-r from-emerald-500 to-teal-500 text-white rounded-t-lg print:bg-gray-100 print:text-black">
              <div className="flex items-start justify-between">
                <div>
                  <CardTitle className="text-2xl flex items-center gap-2">
                    <Brain className="h-6 w-6" />
                    NeuroScreen Clinical Report
                  </CardTitle>
                  <CardDescription className="text-white/80 print:text-gray-600 mt-1">
                    Autism Spectrum Screening Summary
                  </CardDescription>
                </div>
                <div className="text-right text-sm">
                  <p className="font-medium">{report.userName}</p>
                  <p className="opacity-80">{formatDate(report.generatedAt)}</p>
                </div>
              </div>
            </CardHeader>
            <CardContent className="p-6">
              {/* Risk Overview */}
              <div className="grid md:grid-cols-3 gap-4 mb-6">
                <div className={cn("p-4 rounded-lg", getRiskColor(report.latestScreening.riskLevel))}>
                  <div className="flex items-center gap-2 mb-2">
                    {getRiskIcon(report.latestScreening.riskLevel)}
                    <span className="font-medium">Risk Level</span>
                  </div>
                  <p className="text-2xl font-bold">{report.latestScreening.riskLevel}</p>
                </div>
                <div className="p-4 rounded-lg bg-teal-50 dark:bg-teal-950 text-teal-600 dark:text-teal-400">
                  <div className="flex items-center gap-2 mb-2">
                    <BarChart3 className="h-5 w-5" />
                    <span className="font-medium">Probability</span>
                  </div>
                  <p className="text-2xl font-bold">{(report.latestScreening.probability * 100).toFixed(1)}%</p>
                </div>
                <div className="p-4 rounded-lg bg-purple-50 dark:bg-purple-950 text-purple-600 dark:text-purple-400">
                  <div className="flex items-center gap-2 mb-2">
                    <Target className="h-5 w-5" />
                    <span className="font-medium">Confidence</span>
                  </div>
                  <p className="text-2xl font-bold">{report.latestScreening.confidence}</p>
                </div>
              </div>

              {/* Scores Grid */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                {report.latestScreening.aq10Total && (
                  <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-900">
                    <p className="text-sm text-muted-foreground">AQ-10 Total</p>
                    <p className="text-xl font-bold">{report.latestScreening.aq10Total}/10</p>
                  </div>
                )}
                {report.latestScreening.socialScore && (
                  <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-900">
                    <p className="text-sm text-muted-foreground">Social Score</p>
                    <p className="text-xl font-bold">{report.latestScreening.socialScore}</p>
                  </div>
                )}
                {report.latestScreening.attentionScore && (
                  <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-900">
                    <p className="text-sm text-muted-foreground">Attention Score</p>
                    <p className="text-xl font-bold">{report.latestScreening.attentionScore}</p>
                  </div>
                )}
                {report.latestScreening.physicalScore && (
                  <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-900">
                    <p className="text-sm text-muted-foreground">Physical Assessment</p>
                    <p className="text-xl font-bold">{report.latestScreening.physicalScore}/5</p>
                  </div>
                )}
              </div>

              {/* Contributing Factors */}
              <div className="mb-6">
                <h3 className="font-semibold mb-3 flex items-center gap-2">
                  <TrendingUp className="h-5 w-5 text-primary" />
                  Top Contributing Factors
                </h3>
                <div className="space-y-2">
                  {report.latestScreening.contributingFactors.slice(0, 5).map((factor, idx) => (
                    <div
                      key={idx}
                      className="flex items-center justify-between p-3 rounded-lg bg-slate-50 dark:bg-slate-900"
                    >
                      <span className="text-sm">{factor.feature}</span>
                      <div className="flex items-center gap-2">
                        <Badge variant="outline">{factor.importance.toFixed(1)}%</Badge>
                        <Badge
                          variant={factor.direction === "positive" ? "default" : "secondary"}
                          className="text-xs"
                        >
                          {factor.direction}
                        </Badge>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Therapy Progress */}
          {includeTherapyProgress && report.therapyProgress.totalTasks > 0 && (
            <Card className="border-0 shadow-lg print:shadow-none print:border">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Target className="h-5 w-5 text-primary" />
                  Therapy Progress
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid md:grid-cols-3 gap-4 mb-4">
                  <div className="p-4 rounded-lg bg-slate-50 dark:bg-slate-900 text-center">
                    <p className="text-3xl font-bold text-primary">{report.therapyProgress.totalTasks}</p>
                    <p className="text-sm text-muted-foreground">Total Tasks</p>
                  </div>
                  <div className="p-4 rounded-lg bg-slate-50 dark:bg-slate-900 text-center">
                    <p className="text-3xl font-bold text-green-500">{report.therapyProgress.completedTasks}</p>
                    <p className="text-sm text-muted-foreground">Completed</p>
                  </div>
                  <div className="p-4 rounded-lg bg-slate-50 dark:bg-slate-900 text-center">
                    <p className="text-3xl font-bold text-teal-500">{report.therapyProgress.completionRate}%</p>
                    <p className="text-sm text-muted-foreground">Completion Rate</p>
                  </div>
                </div>

                {Object.keys(report.therapyProgress.tasksByCategory).length > 0 && (
                  <div>
                    <h4 className="font-medium mb-2">Tasks by Category</h4>
                    <div className="flex flex-wrap gap-2">
                      {Object.entries(report.therapyProgress.tasksByCategory).map(([category, count]) => (
                        <Badge key={category} variant="outline" className="py-1">
                          {category}: {report.therapyProgress.completedByCategory[category] || 0}/{count}
                        </Badge>
                      ))}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          )}

          {/* Screening History */}
          {report.screeningHistory.length > 1 && (
            <Card className="border-0 shadow-lg print:shadow-none print:border">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Calendar className="h-5 w-5 text-primary" />
                  Screening History
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {report.screeningHistory.map((screening, idx) => (
                    <div
                      key={idx}
                      className="flex items-center justify-between p-3 rounded-lg bg-slate-50 dark:bg-slate-900"
                    >
                      <div className="flex items-center gap-3">
                        <div className={cn(
                          "w-3 h-3 rounded-full",
                          screening.riskLevel === "High" ? "bg-red-500" :
                            screening.riskLevel === "Moderate" ? "bg-amber-500" : "bg-green-500"
                        )} />
                        <span className="text-sm">
                          {new Date(screening.date).toLocaleDateString()}
                        </span>
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge variant="outline">{screening.riskLevel}</Badge>
                        <span className="text-sm font-medium">
                          {(screening.probability * 100).toFixed(1)}%
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* AI Clinical Summary */}
          <Card className="border-0 shadow-lg print:shadow-none print:border">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="h-5 w-5 text-primary" />
                Clinical Summary
              </CardTitle>
              <CardDescription>
                AI-generated analysis based on screening data
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="prose prose-sm dark:prose-invert max-w-none">
                <ReactMarkdown>{report.clinicalSummary}</ReactMarkdown>
              </div>
            </CardContent>
          </Card>

          {/* Disclaimer */}
          <Card className="border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-950/50">
            <CardContent className="py-4">
              <div className="flex gap-3">
                <AlertTriangle className="h-5 w-5 text-amber-500 flex-shrink-0 mt-0.5" />
                <div className="text-sm text-amber-700 dark:text-amber-300">
                  <p className="font-medium mb-1">Important Disclaimer</p>
                  <p>
                    This report is generated by NeuroScreen, an AI-powered autism screening tool.
                    It is intended for informational purposes only and should NOT be considered
                    a medical diagnosis. Please consult with qualified healthcare professionals
                    for proper evaluation, diagnosis, and treatment recommendations.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          body * {
            visibility: hidden;
          }
          .print\\:hidden {
            display: none !important;
          }
          #report-content, #report-content * {
            visibility: visible;
          }
          #report-content {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
          }
        }
      `}</style>
    </div>
  )
}
